sudo: required
services:
  - docker

before_install:
  - docker build -t cbadez10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run cbadez10/react-test npm test -- --coverage

after_success:
  - docker build -t cbadez10/multi-client ./client
  - docker build -t cbadez10/multi-nginx ./nginx
  - docker build -t cbadez10/multi-server ./server
  - docker build -t cbadez10/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push cbadez10/multi-client
  - docker push cbadez10/multi-nginx
  - docker push cbadez10/multi-server
  - docker push cbadez10/multi-worker
